name       : python-pysocks
version    : 1.7.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/bd/11/293dd436aea955d45fc4e8a35b6ae7270f5b8e00b53cf6c024c83b657a11/PySocks-1.7.1.tar.gz : 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
license    : BSD-3-Clause
component  : programming-python
summary    : A Python SOCKS client module
description: |
    A Python SOCKS client module
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
